export const LOADING_DATA = "LOADING_DATA";
export const SET_TRACKS = "SET_TRACKS";
export const LOADING_FAILED = "LOADING_FAILED";
export const LOADING_PLAYBACKINSTANCE = "LOADING_PLAYBACKINSTANCE";
export const SET_PLAYBACKINSTANCE = "SET_PLAYBACKINSTANCE";
export const SET_PLAY = "SET_PLAY";
export const SET_CURRENT_INDEX = "SET_CURRENT_INDEX";
export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK";